services:
  - type: web
    name: kongopay-api
    runtime: node
    repo: https://github.com/Lwango1/kongopay
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://kongopay.vercel.app
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FINNHUB_API_KEY
        value: d8q01kpr01qr03ncmlngd8q01kpr01qr03ncmlo0
      - key: BINANCE_API_KEY
        sync: false
      - key: BINANCE_API_SECRET
        sync: false
      - key: P2P_ADMIN_UID
        value: TOkdYT0y2mR0EZ3FGnXniQbTuGk2
      - key: ADMIN_UID
        value: TOkdYT0y2mR0EZ3FGnXniQbTuGk2
      - key: P2P_ADMIN_BINANCE_WALLET
        value: 0xb365cfcd75f6425e05eb072a7c97032c8d21ad28
      - key: AIRTEL_MONEY_NUMBER
        value: "+243996710821"
      - key: ORANGE_MONEY_NUMBER
        value: "+243996710821"
      - key: MPESA_NUMBER
        value: "+243996710821"
      - key: PORT
        value: "10000"
